services:
  mainservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      redisserver:
        condition: service_healthy
    volumes:
      - .:/app
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3
    networks:
      - shared-net

  redisserver:
    build: 
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - shared-net

  nginxserver:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/etc/staticfiles
      - ./media:/etc/media
    depends_on:
      mainservice:
        condition: service_started
    networks:
      - shared-net


networks:
  shared-net:
    driver: bridge